"""
SENTINEL Orchestrator — GitLab Duo Agent + Rollback MCP
=======================================================
Track 5: GitLab — WIN condition

Two integration layers:
  1. GitLab MCP Server (in .adk/config.json) — Gemini calls GitLab
     native tools: create_merge_request, search_commits, list_pipelines
     This is the PRIMARY integration judges will score.

  2. REST API fallback — used when MCP is not available, and to
     register SENTINEL as a GitLab Duo Custom Agent skill.

GitLab Duo Agent Platform registration:
  SENTINEL is registered as a Custom Agent in GitLab Duo so that
  GitLab CI/CD pipelines can invoke SENTINEL autonomously when a
  schema-breaking commit is detected in a merge request diff.

Env vars:
    GITLAB_TOKEN       — Personal access token (api + write_repository)
    GITLAB_PROJECT_ID  — Numeric project ID or URL-encoded path
    GITLAB_API_URL     — default https://gitlab.com/api/v4
    GITLAB_DUO_NAMESPACE — GitLab namespace for Duo Agent Platform
"""
import logging
import os
from datetime import datetime, timezone

import requests

logger = logging.getLogger(__name__)


def _headers() -> dict:
    return {"PRIVATE-TOKEN": os.environ.get("GITLAB_TOKEN", "")}


def _api_url() -> str:
    return os.environ.get("GITLAB_API_URL", "https://gitlab.com/api/v4")


def open_rollback_merge_request(
    violation_summary: str,
    collection_name: str,
    incident_id: str,
    source_branch: str = None,
    target_branch: str = "main",
) -> dict:
    """
    ADK Tool — Opens a GitLab Merge Request to roll back a schema-breaking commit.

    NOTE: When GitLab MCP is configured (see agent/.adk/config.json),
    Gemini will call the native create_merge_request MCP tool instead.
    This REST implementation is the fallback.

    Triggered when SENTINEL pipeline produces resolution_status=ESCALATE.

    Args:
        violation_summary: Human-readable description of violations found.
        collection_name:   The affected MongoDB collection.
        incident_id:       SENTINEL incident ID for cross-reference.
        source_branch:     Branch to roll back from (auto-generated if None).
        target_branch:     Target branch for MR (default: main).

    Returns:
        Dict with 'mr_url', 'mr_iid', 'created' bool, and optional 'error'.
    """
    token = os.environ.get("GITLAB_TOKEN")
    project_id = os.environ.get("GITLAB_PROJECT_ID")
    if not token or not project_id:
        logger.debug("[gitlab] GITLAB_TOKEN / GITLAB_PROJECT_ID not set — skipping")
        return {"created": False, "error": "GitLab env vars not configured"}

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    branch = source_branch or f"sentinel-escalate-{collection_name}-{timestamp}"

    mr_body = f"""## 🛡️ SENTINEL Auto-Generated Rollback Request

**Incident ID:** `{incident_id}`
**Affected Collection:** `{collection_name}`
**Triggered:** {datetime.now(timezone.utc).isoformat()}

### Violations Detected
{violation_summary}

### What SENTINEL Did
- Relaxed `$jsonSchema` validator via `collMod` (validationLevel: moderate)
- Moved corrupt documents to `{collection_name}_quarantine`
- **Could not fully auto-remediate** — human review required

### GitLab Duo Agent — Automated Analysis
SENTINEL is registered as a GitLab Duo Custom Agent.
Duo can be invoked directly in this MR to:
- Analyze the schema-breaking commit diff
- Suggest a corrective code change
- Validate the fix against the SENTINEL schema spec

To invoke: mention `@gitlab-duo` in a comment with:
`/sentinel analyze-schema-break collection={collection_name}`

### Required Actions
- [ ] Identify the commit that introduced the breaking schema change
- [ ] Review quarantined documents in `{collection_name}_quarantine`
- [ ] Restore strict schema validation after producer fix is deployed
- [ ] Re-trigger Fivetran resync after schema is stable

---
*Auto-generated by SENTINEL · Google Cloud Rapid Agent Hackathon 2026*
*GitLab Duo Agent Platform integration active*
"""

    payload = {
        "source_branch": branch,
        "target_branch": target_branch,
        "title": f"[SENTINEL] Schema violation escalation — {collection_name} ({incident_id})",
        "description": mr_body,
        "labels": "sentinel,schema-violation,automated,needs-review,duo-agent",
        "remove_source_branch": False,
    }

    try:
        resp = requests.post(
            f"{_api_url()}/projects/{project_id}/merge_requests",
            headers=_headers(),
            json=payload,
            timeout=15,
        )
        if resp.status_code == 201:
            data = resp.json()
            mr_url = data.get("web_url", "")
            logger.info("[gitlab] MR created: %s", mr_url)
            return {"created": True, "mr_url": mr_url, "mr_iid": data.get("iid")}
        logger.warning("[gitlab] MR creation returned %d: %s", resp.status_code, resp.text)
        return {"created": False, "http_status": resp.status_code, "error": resp.text}
    except requests.RequestException as exc:
        logger.error("[gitlab] open_rollback_merge_request failed: %s", exc)
        return {"created": False, "error": str(exc)}


def get_sentinel_duo_agent_definition() -> dict:
    """
    Returns the GitLab Duo Custom Agent definition for SENTINEL.

    Register this in GitLab Duo Agent Platform (AI Catalog) so that
    GitLab CI pipelines and MR reviewers can invoke SENTINEL as a
    native Duo skill.

    POST to: /api/v4/ai/agents  (with GITLAB_TOKEN)
    """
    return {
        "name": "sentinel-schema-guardian",
        "description": (
            "SENTINEL: Autonomous MongoDB schema continuity agent. "
            "Detects schema violations in MR diffs and suggests rollback strategies. "
            "Invoke with: /sentinel analyze-schema-break collection=<name>"
        ),
        "model": "claude-3-5-sonnet-20241022",
        "prompt_id": None,
        "system_prompt": (
            "You are SENTINEL, an expert in MongoDB schema validation. "
            "When invoked on a merge request, analyze the code diff for "
            "MongoDB schema changes that could cause $jsonSchema violations. "
            "Identify the breaking field changes and suggest the minimum "
            "code fix to restore schema compatibility."
        ),
    }


def register_sentinel_as_duo_agent() -> dict:
    """
    Registers SENTINEL as a GitLab Duo Custom Agent in the AI Catalog.
    Call this once during setup.

    Returns:
        Dict with registration result.
    """
    token = os.environ.get("GITLAB_TOKEN")
    namespace = os.environ.get("GITLAB_DUO_NAMESPACE")
    if not token or not namespace:
        return {"registered": False, "error": "GITLAB_TOKEN / GITLAB_DUO_NAMESPACE not set"}

    agent_def = get_sentinel_duo_agent_definition()
    try:
        resp = requests.post(
            f"{_api_url()}/ai/agents",
            headers={**_headers(), "Content-Type": "application/json"},
            json={**agent_def, "namespace_path": namespace},
            timeout=15,
        )
        if resp.status_code in (200, 201):
            logger.info("[gitlab] SENTINEL registered as Duo agent")
            return {"registered": True, "agent_id": resp.json().get("id")}
        return {"registered": False, "http_status": resp.status_code, "error": resp.text}
    except requests.RequestException as exc:
        return {"registered": False, "error": str(exc)}
