"""
SENTINEL Orchestrator — GitLab Rollback Agent
==============================================
Partner Track: GitLab

When SENTINEL reports resolution_status=ESCALATE (automated remediation
was incomplete or violations are CRITICAL), this agent opens a GitLab
Merge Request flagging the schema-breaking commit for human review and
automated rollback.

This closes the Layer 2 self-healing loop:
  Elastic log alert → GitLab MR rollback → SENTINEL schema patch → Fivetran resync

Env vars required:
    GITLAB_TOKEN     — GitLab personal access token (api + write_repository scopes)
    GITLAB_PROJECT_ID — numeric project ID or URL-encoded path e.g. "mmm-byte%2FSENTINEL"
    GITLAB_API_URL   — default https://gitlab.com/api/v4
"""
import logging
import os
from datetime import datetime, timezone

import requests

logger = logging.getLogger(__name__)


def _headers() -> dict:
    return {"PRIVATE-TOKEN": os.environ.get("GITLAB_TOKEN", "")}


def _api_url() -> str:
    return os.environ.get("GITLAB_API_URL", "https://gitlab.com/api/v4")


def open_rollback_merge_request(
    violation_summary: str,
    collection_name: str,
    incident_id: str,
    source_branch: str = None,
    target_branch: str = "main",
) -> dict:
    """
    ADK Tool — Opens a GitLab Merge Request to roll back a schema-breaking commit.

    Triggered when SENTINEL pipeline produces resolution_status=ESCALATE,
    signalling that human-reviewed rollback is required.

    Args:
        violation_summary: Human-readable description of violations found.
        collection_name:   The affected MongoDB collection.
        incident_id:       SENTINEL incident ID for cross-reference.
        source_branch:     Branch to roll back from (auto-generated if None).
        target_branch:     Target branch for MR (default: main).

    Returns:
        Dict with 'mr_url', 'mr_iid', 'created' bool, and optional 'error'.
    """
    token = os.environ.get("GITLAB_TOKEN")
    project_id = os.environ.get("GITLAB_PROJECT_ID")
    if not token or not project_id:
        logger.debug("[gitlab] GITLAB_TOKEN / GITLAB_PROJECT_ID not set — skipping")
        return {"created": False, "error": "GitLab env vars not configured"}

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    branch = source_branch or f"sentinel-escalate-{collection_name}-{timestamp}"

    mr_body = f"""## 🛡️ SENTINEL Auto-Generated Rollback Request

**Incident ID:** `{incident_id}`  
**Affected Collection:** `{collection_name}`  
**Triggered:** {datetime.now(timezone.utc).isoformat()}  

### Violations Detected
{violation_summary}

### What SENTINEL Did
- Relaxed `$jsonSchema` validator via `collMod` (validationLevel: moderate)
- Moved corrupt documents to `{collection_name}_quarantine`
- **Could not fully auto-remediate** — human review required

### Required Actions
- [ ] Identify the commit that introduced the breaking schema change
- [ ] Review quarantined documents in `{collection_name}_quarantine`
- [ ] Restore strict schema validation after producer fix is deployed
- [ ] Re-trigger Fivetran resync after schema is stable

---
*Auto-generated by SENTINEL · Google Cloud Rapid Agent Hackathon 2026*
"""

    payload = {
        "source_branch": branch,
        "target_branch": target_branch,
        "title": f"[SENTINEL] Schema violation escalation — {collection_name} ({incident_id})",
        "description": mr_body,
        "labels": "sentinel,schema-violation,automated,needs-review",
        "remove_source_branch": False,
    }

    try:
        resp = requests.post(
            f"{_api_url()}/projects/{project_id}/merge_requests",
            headers=_headers(),
            json=payload,
            timeout=15,
        )
        if resp.status_code == 201:
            data = resp.json()
            mr_url = data.get("web_url", "")
            logger.info("[gitlab] MR created: %s", mr_url)
            return {"created": True, "mr_url": mr_url, "mr_iid": data.get("iid")}
        else:
            logger.warning("[gitlab] MR creation returned %d: %s", resp.status_code, resp.text)
            return {"created": False, "http_status": resp.status_code, "error": resp.text}
    except requests.RequestException as exc:
        logger.error("[gitlab] open_rollback_merge_request failed: %s", exc)
        return {"created": False, "error": str(exc)}
